import { useEffect, useState } from "react";
import API from "../api/api";
import {
  FaShieldAlt,
  FaBug,
  FaClock,
  FaBroadcastTower,
} from "react-icons/fa";

function AlertsPage({ websiteId, preview = false }) {
  const [alerts, setAlerts] = useState([]);

  const fetchAlerts = async () => {
    try {
      const response = await API.get("/history", { params: { website_id: websiteId } });

      const logs = response.data.data || [];

      // Sirf attack alerts (BENIGN remove)
      const attackAlerts = logs.filter(
        (item) => item.attack_name !== "BENIGN"
      );

      setAlerts(preview ? attackAlerts.slice(0, 5) : attackAlerts);
    } catch (error) {
      console.error("Alerts Error:", error);
    }
  };

  useEffect(() => {
    fetchAlerts();

    const interval = setInterval(fetchAlerts, 3000);
    return () => clearInterval(interval);
  }, [preview, websiteId]);

  const getSeverity = (attack) => {
    if (["DDoS", "Heartbleed"].includes(attack)) return "Critical";

    if (
      [
        "DoS Hulk",
        "DoS GoldenEye",
        "DoS Slowloris",
        "DoS Slowhttptest",
        "PortScan",
        "Bot",
      ].includes(attack)
    )
      return "High";

    if (
      [
        "FTP-Patator",
        "SSH-Patator",
        "Infiltration",
        "Web Attack Brute Force",
        "Web Attack SQL Injection",
        "Web Attack XSS",
      ].includes(attack)
    )
      return "Medium";

    return "Low";
  };

  const getSeverityStyle = (severity) => {
    switch (severity) {
      case "Critical":
        return {
          bg: "bg-red-100 border-red-300",
          text: "text-red-700",
          badge: "bg-red-600 text-white",
        };

      case "High":
        return {
          bg: "bg-orange-100 border-orange-300",
          text: "text-orange-700",
          badge: "bg-orange-500 text-white",
        };

      case "Medium":
        return {
          bg: "bg-yellow-100 border-yellow-300",
          text: "text-yellow-700",
          badge: "bg-yellow-500 text-white",
        };

      default:
        return {
          bg: "bg-green-100 border-green-300",
          text: "text-green-700",
          badge: "bg-green-600 text-white",
        };
    }
  };

  return (
    <div className="bg-white rounded-3xl border border-gray-200 shadow-sm p-6">
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-3">
            <FaBroadcastTower className="text-red-600" />
            Security Alert Center
          </h2>

          <p className="text-sm text-gray-500 mt-1">
            Real-time intrusion alerts generated by Hybrid Classifier.
          </p>
        </div>

        <span className="bg-red-100 text-red-700 px-3 py-2 rounded-full text-xs font-bold">
          LIVE ALERTS
        </span>
      </div>

      {/* Empty */}
      {alerts.length === 0 && (
        <div className="bg-green-50 border border-green-200 rounded-2xl p-8 text-center">
          <FaShieldAlt className="mx-auto text-5xl text-green-600 mb-4" />

          <h3 className="text-xl font-bold text-green-700">
            System Secure
          </h3>

          <p className="text-gray-500 mt-2">
            No malicious network traffic detected.
          </p>
        </div>
      )}

      {/* Alerts */}
      <div className="space-y-4">
        {alerts.map((alert) => {
          const severity = getSeverity(alert.attack_name);
          const style = getSeverityStyle(severity);

          return (
            <div
              key={alert.id}
              className={`rounded-2xl border p-5 ${style.bg}`}
            >
              <div className="flex justify-between items-start gap-4">
                {/* Left */}
                <div className="flex gap-4">
                  <div className="w-12 h-12 rounded-xl bg-white flex items-center justify-center shadow-sm">
                    <FaBug className={`text-xl ${style.text}`} />
                  </div>

                  <div>
                    <h3 className={`font-bold text-lg ${style.text}`}>
                      {alert.attack_name}
                    </h3>

                    <p className="text-gray-600 text-sm mt-1">
                      Network intrusion detected by AI Hybrid Classifier.
                    </p>

                    <div className="flex flex-wrap gap-3 mt-3 text-sm text-gray-700">
                      <span>
                        Source IP:{" "}
                        <b>{alert.client_ip || "Unknown"}</b>
                      </span>

                      <span>
                        Port:{" "}
                        <b>{alert.destination_port || "443"}</b>
                      </span>

                      <span>
                        Confidence:{" "}
                        <b>
                          {(Number(alert.confidence) * 100).toFixed(2)}%
                        </b>
                      </span>
                    </div>
                  </div>
                </div>

                {/* Severity */}
                <span
                  className={`px-3 py-2 rounded-full text-xs font-bold ${style.badge}`}
                >
                  {severity}
                </span>
              </div>

              {/* Footer */}
              <div className="flex justify-between items-center mt-4 text-xs text-gray-600 border-t pt-3">
                <span className="flex items-center gap-2">
                  <FaClock />
                  {new Date(alert.created_at).toLocaleString()}
                </span>

                <span className="font-semibold text-red-600">
                  Threat Detected
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Footer */}
      {!preview && (
        <div className="mt-6 text-center text-sm text-green-600 font-semibold">
          â— Auto Refresh Every 3 Seconds
        </div>
      )}
    </div>
  );
}

export default AlertsPage;
