import { useEffect, useState } from "react";
import API from "../api/api";
import {
  FaShieldAlt,
  FaBug,
  FaClock,
  FaNetworkWired,
} from "react-icons/fa";

function PredictionTable({ setSelectedPrediction }) {
  const [predictions, setPredictions] = useState([]);

  const fetchPredictions = async () => {
    try {
      const response = await API.get("/history");
      setPredictions(response.data.data || []);
    } catch (error) {
      console.error("Prediction History Error:", error);
    }
  };

  useEffect(() => {
    fetchPredictions();

    const interval = setInterval(fetchPredictions, 3000);
    return () => clearInterval(interval);
  }, []);

  // Severity Mapping
  const getSeverity = (attack) => {
    if (!attack) return "Low";

    if (["DDoS", "Heartbleed"].includes(attack)) return "Critical";

    if (
      [
        "DoS Hulk",
        "DoS GoldenEye",
        "DoS Slowloris",
        "DoS Slowhttptest",
        "PortScan",
        "Bot",
      ].includes(attack)
    )
      return "High";

    if (
      [
        "FTP-Patator",
        "SSH-Patator",
        "Infiltration",
        "Web Attack Brute Force",
        "Web Attack SQL Injection",
        "Web Attack XSS",
      ].includes(attack)
    )
      return "Medium";

    return "Low";
  };

  const getSeverityStyle = (severity) => {
    switch (severity) {
      case "Critical":
        return "bg-red-100 text-red-700";
      case "High":
        return "bg-orange-100 text-orange-700";
      case "Medium":
        return "bg-yellow-100 text-yellow-700";
      default:
        return "bg-green-100 text-green-700";
    }
  };

  const getAttackIcon = (attack) => {
    return attack === "BENIGN" ? (
      <FaShieldAlt className="text-green-600" />
    ) : (
      <FaBug className="text-red-600" />
    );
  };

  return (
    <div className="bg-white rounded-3xl shadow-sm border border-gray-200 p-6 mt-8">
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-800">
            Live Threat Detection Logs
          </h2>

          <p className="text-sm text-gray-500">
            Real-time network intrusion predictions generated by Hybrid
            Classifier.
          </p>
        </div>

        <span className="bg-red-100 text-red-700 px-3 py-2 rounded-full text-xs font-bold">
          LIVE LOGS
        </span>
      </div>

      {/* Table */}
      <div className="overflow-x-auto rounded-2xl border border-gray-200">
        <table className="min-w-full text-sm">
          <thead className="bg-slate-900 text-white">
            <tr>
              <th className="p-3 text-left">Attack</th>
              <th className="p-3 text-left">Severity</th>
              <th className="p-3 text-left">Confidence</th>
              <th className="p-3 text-left">Source IP</th>
              <th className="p-3 text-left">Destination Port</th>
              <th className="p-3 text-left">Detected At</th>
            </tr>
          </thead>

          <tbody>
            {predictions.length === 0 ? (
              <tr>
                <td
                  colSpan="6"
                  className="text-center py-10 text-gray-400"
                >
                  No prediction logs available.
                </td>
              </tr>
            ) : (
              predictions.map((item) => {
                const severity = getSeverity(item.attack_name);

                return (
                  <tr
                    key={item.id}
                    onClick={() =>
                      setSelectedPrediction &&
                      setSelectedPrediction(item)
                    }
                    className="border-b hover:bg-blue-50 cursor-pointer transition"
                  >
                    {/* Attack */}
                    <td className="p-3">
                      <div className="flex items-center gap-2 font-semibold">
                        {getAttackIcon(item.attack_name)}
                        {item.attack_name}
                      </div>
                    </td>

                    {/* Severity */}
                    <td className="p-3">
                      <span
                        className={`px-3 py-1 rounded-full text-xs font-bold ${getSeverityStyle(
                          severity
                        )}`}
                      >
                        {severity}
                      </span>
                    </td>

                    {/* Confidence */}
                    <td className="p-3 font-semibold text-blue-700">
                      {(Number(item.confidence) * 100).toFixed(2)}%
                    </td>

                    {/* Source IP */}
                    <td className="p-3">
                      <div className="flex items-center gap-2 text-gray-700">
                        <FaNetworkWired className="text-blue-600" />
                        {item.client_ip || "Unknown"}
                      </div>
                    </td>

                    {/* Port */}
                    <td className="p-3 font-medium">
                      {item.destination_port || "443"}
                    </td>

                    {/* Time */}
                    <td className="p-3 text-gray-600">
                      <div className="flex items-center gap-2">
                        <FaClock className="text-gray-500" />
                        {new Date(item.created_at).toLocaleString()}
                      </div>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="flex justify-between mt-5 text-sm text-gray-500">
        <span>Total Logs : {predictions.length}</span>

        <span className="text-green-600 font-semibold">
          ● Auto Refresh Every 3 Seconds
        </span>
      </div>
    </div>
  );
}

export default PredictionTable;